version: "3.9"
services:
  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    networks: 
      - remoteCodeExecutionEngineNetwork
  
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
    networks: 
      - remoteCodeExecutionEngineNetwork
  
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/var/lib/redis
    networks:
      - remoteCodeExecutionEngineNetwork
  
  backend:
    image: backend
    build: ./backend
    container_name: backend
    ports:
      - "5005:5005"
    networks:
      - remoteCodeExecutionEngineNetwork

volumes:
  rabbitmq:
  redis:
  
networks:
  remoteCodeExecutionEngineNetwork:
    driver: bridge
    name: remoteCodeExecutionEngine